import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/config/font";

export const metadata: Metadata = {
	title: {
		template: "%s - Teslo | Shop",
		default: "Teslo | Shop",
	},
	description: "Generated by Teslo | Shop",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen`}
			>
				{children}
			</body>
		</html>
	);
}
